### ISSUE TITLE
0.85 to 0.9 migration

### ISSUE THREAD

**Issue by sole-practitioner** [freemed/freemed#13]
I have managed to foo bar 0.85, after a couple of hours trying to get it running again, I decided to try 0.9 instead.  I now have that running on a new virtual Debian7.9 (on Windows HyperV).  How do I migrate data from old database?  Is it as simple as simply moving the database from the old server to the new server?  I expect 0.9 uses different fields, so I would be afraid that would wreck things.  

If I could get from old database the patients, insurance, diagnosis from old, that would get me up and running,  Maybe I can merge just those tables (I'm talking a bit over my own head!). Using phpmyadmin, I seem to only be able to replace tables, not "merge".

-tbh

**Comment by jbuchbinder** [comment]
There is an upgrade script in the ```scripts``` directory, which can be used to change the table layouts from 0.8.x to 0.9.x. If you execute ```php scripts/upgrade.php``` it should migrate the definitions for you.

**(Please remember to back up your database before doing this.)**
