### ISSUE TITLE
HL7 for Lab Results

### ISSUE THREAD

**Issue by jelord** [freemed/freemed#21]
Has anyone successfully used FreeMed for generating/handling lab results data via HL7?

Additionally, how difficult do you think it would be to expand the existing HL7 generator/handlers to include ORM message types?

**Comment by jbuchbinder** [comment]
The 0.8.x version originally had some classes to handle separate message types, including lab types.

That code lives in `lib/org/freemedsoftware/core` in handlers and generators like:

```
Generator_HL7v2_A04.class.php
Generator_HL7v2_A08.class.php
Handler_HL7v2_A04.class.php
Handler_HL7v2_A08.class.php
Handler_HL7v2.class.php
Handler_HL7v2_R01.class.php
Handler_HL7v2_S12.class.php
Handler_HL7v2_S15.class.php
```

New message types are dynamically loaded by message type, so creating a new handler will expand the ability to handle that message type. Generators have to be "hooked" into the code to produce output. For example, `A04` generation in `lib/org/freemedsoftware/module/PatientModule.class.php`:

```
        protected function add_post ( $id, $data ) {
                $m = CreateObject( 'org.freemedsoftware.core.Generator_HL7v2_A04' );
                $mirth = CreateObject( 'org.freemedsoftware.core.MirthExport' );
                if ($m) {
                        $out = $m->generate( $id );
                        $mirth->SendMessage( $out );
                }
        } // end method add_post
```

(You'll notice that we use "Mirth" as a bridge to handle the intricacies of piping the export somewhere. It's wonderfully free and available, although I believe it's called "Mirth Connect" now.)
